---
title: "Class 11: Introduction to Genome Informatics"
author: 'Arshiya Zarmahd (PID: A16247996)'
date: "2024-05-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Proportion of Homozygous (*G|G*) Individuals in a Population

Downloaded a CSV file from Ensemble < https://useast.ensembl.org/Homo_sapiens/Variation/Sample?db=core;r=17:39894595-39895595;v=rs8067378;vdb=variation;vf=959672880 >

Here we read this CSV file:

```{r}
mxl <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
head(mxl)
```

```{r}
table(mxl$Genotype..forward.strand.)
```

```{r}
table(mxl$Genotype..forward.strand.) / nrow(mxl) * 100
```

Now lets look at a different population. We picked the GBR population. 

```{r}
gbr <- read.csv("373522-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
head(gbr)
```

What are the proportions of each genotype?

```{r}
round(table(gbr$Genotype..forward.strand.) / nrow(gbr) * 100, 2)

```













